**1. Write a Python Program to Add Two Matrices.**

In [42]:
# see
X = np.array([[1,2],
     [3,5],
     [8,9]])
Y = np.array([[4,5],
     [8,4],
     [3,7]])
import numpy as np
add = np.add(X,Y)
print("The sum of matrices\n",X,"   and \n\n", Y, "    is : \n\n ",add)

The sum of matrices
 [[1 2]
 [3 5]
 [8 9]]    and 

 [[4 5]
 [8 4]
 [3 7]]     is : 

  [[ 5  7]
 [11  9]
 [11 16]]


**2. Write a Python Program to Multiply Two Matrices**

In [41]:
import numpy as np
X = np.array([[1,2],
     [3,5],
     [8,9]])
Y = np.array([[4,5],
     [8,4]])

multiply = np.dot(X,Y)
print("The multiplication of matrices\n",X,"   and \n\n", Y, "    is : \n\n ",multiply)

The multiplication of matrices
 [[1 2]
 [3 5]
 [8 9]]    and 

 [[4 5]
 [8 4]]     is : 

  [[ 20  13]
 [ 52  35]
 [104  76]]


**3. Write a Python Program to Transpose a Matrix.**

In [35]:
Z = np.array([[1,3,5],
     [2,4,6],
     [7,4,1]])

transpos = np.transpose(Z)
print("The transpose of \n",Z,"  is :\n\n",transpos)

The transpose of 
 [[1 3 5]
 [2 4 6]
 [7 4 1]]   is :

 [[1 2 7]
 [3 4 4]
 [5 6 1]]


**4. Write a Python Program to Sort Words in Alphabetic Order.**

In [51]:
a = input("Enter a sentence : ")
sentence = [i.lower() for i in a.split()]
sentence.sort()
print("\nThe sorted sentence in Alphabetical order is : \n ",' '.join(sentence))

Enter a sentence : Write a Python Program to Sort Words in Alphabetic Order

The sorted sentence in Alphabetical order is : 
  a alphabetic in order program python sort to words write


**5. Write a Python Program to Remove Punctuation From a String?**

In [58]:
a = input("Enter a sentence : ")
def punctuation_remover(a):    
    line = ""
    import string
    for i in a:
        if i not in string.punctuation:
            line = line + i
    return line
print(punctuation_remover(a))

Enter a sentence : Write a Python Program to Remove Punc/tuation From a String.;'.;';'
Write a Python Program to Remove Punctuation From a String
