**Question 1:
Write a program that calculates and prints the value according to the given formula:**\
Q = Square root of [(2 * C * D)/H]\
**Following are the fixed values of C and H:**\
C is 50. H is 30.\
**D is the variable whose values should be input to your program in a comma-separated
sequence.**\
**Example\
Let us assume the following comma separated input sequence is given to the program:**\
100,150,180\
**The output of the program should be:**\
18,22,24



In [31]:
import math
C,H = 50,30
D_variable = input("Enter values of D : ")
D_variable = D_variable.split(",")

output_list = []
for D in D_variable:
    Q = round(math.sqrt((2*C*int(D)) / H))
    output_list.append(str(Q))

print("The respective values of Q : ",",".join(output_list))

Enter values of D : 100,150,180
The respective values of Q :  18,22,24


**Question 2:\
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.\
Note: i=0,1, .. , X-1 ;  j=0,1, .. ,Y-1.\
Example\
Suppose the following inputs are given to the program:**\
3,5\
**Then, the output of the program should be:**\
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

**Solution (i)**

In [23]:
row,col = input("Enter X,Y : ").split(",")
X = int(row)
Y = int(col)
two_d_list = []
for i in range(X):
    row = []
    for j in range(Y):
        row.append(i*j)
    two_d_list.append(row)
print(two_d_list)

Enter X,Y : 3,5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


**Solution (ii)**

In [24]:
import numpy as np
row,col = input("Enter X,Y : ").split(",")
X = int(row)
Y = int(col)
print(np.fromfunction(lambda i,j : i*j, (X,Y)))

Enter X,Y : 3,5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


**Question 3:\
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.\
Suppose the following input is supplied to the program:**\
without,hello,bag,world\
**Then, the output should be:**\
bag,hello,without,world

In [32]:
words = input("Enter words separated by commas : ").split(",")
words.sort()
print("Sorted words : ",",".join(words))

Enter words separated by commas : without,hello,bag,world
Sorted words :  bag,hello,without,world


**Question 4:\
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.\
Suppose the following input is supplied to the program:**\
hello world and practice makes perfect and hello world again\
**Then, the output should be:**\
again and hello makes perfect practice world

In [45]:
words = input("Enter some words : ").split()
a = sorted(set(words))
print("Sorted words :"," ".join(a))

Enter some words : hello world and practice makes perfect and hello world again
Sorted words : again and hello makes perfect practice world


**Question 5:\
Write a program that accepts a sentence and calculate the number of letters and digits.\
Suppose the following input is supplied to the program:**\
hello world! 123\
**Then, the output should be:**\
LETTERS 10\
DIGITS 3

In [48]:
sentence = input("Enter a sentence : ")
LETTERS = 0
DIGITS = 0

for i in sentence:
    if i.isalpha():
        LETTERS = LETTERS + 1
    elif i.isnumeric():
        DIGITS = DIGITS + 1
    else :
        pass
    
print("LETTERS",LETTERS)
print("DIGITS",DIGITS)

Enter a sentence : hello world! 123
LETTERS 10
DIGITS 3


**Question 6:\
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.\
Following are the criteria for checking the password:**\
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12

**Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.\
Example\
If the following passwords are given as input to the program:**\
ABd1234@1,a F1#,2w3E*,2We3345

**Then, the output of the program should be:**\
ABd1234@1

In [70]:
import re
passwords = input("Enter passwords separated by commas : ").split(",")
valid_password = []
for i in passwords:
    if len(i) < 6 or len(i) >12:
        continue
    elif not re.search("[a-z]+",i):
        continue
    elif not re.search("[A-Z]+",i):
        continue
    elif not re.search("[$#@]",i):
        continue
    else:
        valid_password.append(i)
print("Valid password : "," ".join(valid_password))

Enter passwords separated by commas : ABd1234@1,a F1#,2w3E*,2We3345
Valid password :  ABd1234@1
